### ISSUE TITLE
要是不小心让输入法中复制等变成了繁体就再也改不了简体

### ISSUE THREAD

**Issue by zcjxjw** [osfans/trime#113]
像c上的复制等变成了繁体 就是把软件卸载了 再重新装都不能成为简体   只有把手机系统重新装一下才可以成为简体

**Comment by xiaoqun2016** [comment]
看不懂这个问题，手机系统重装了？！ 好大的动作！

**Comment by zcjxjw** [comment]
键盘字符c上档键是复制 除了你自己主动把简体变为繁体 在别的情况下他自己变成了繁体 你就再也改不回简体了  你这个要是能贴图就好了

**Comment by xiaoqun2016** [comment]
你是直接改这个为简体？  

``` yaml
  copy:
    label: "複製"
    send: "Control+c"
```

切到电脑版就可以贴图了：  

![2016-09-17 10 31 50](https://cloud.githubusercontent.com/assets/16501929/18605347/1eacf97c-7c55-11e6-8bfc-69d0593d2d16.png)
