### ISSUE TITLE
“按鍵單獨顏色或標籤:key_text_color、key_back_color”如何使用？

### ISSUE THREAD

**Issue by zaqzrh** [osfans/trime#116]
Commits on Oct 12, 2016
“按鍵單獨顏色或標籤:key_text_color、key_back_color”

请问这个新功能，能不能独立定义某个具体按键的“單獨顏色”，
例如a键、b键，能不能这样定义
-{click: 'a', key_back_color: 0xffeceff1 }
-{click: 'b', key_back_color: 0xff000000 }

@osfans 请实例帮助，谢！

**Comment by osfans** [comment]
是的，也可以定義一個標籤，然後在配色中定義。要測試版才支持，具體可以在菜鳥羣下載測試。

``` yaml
 -{click: 'a', key_back_color: a_color }

lost_temple:
  a_color: 0xffeceff1
```
