### ISSUE TITLE
外接物理键盘时隐藏虚拟键盘

### ISSUE THREAD

**Issue by yanhuacuo** [osfans/trime#1255]
外接键盘下，期待隐藏掉【keys】下的所有键，

当给 `height `  及  `keyboard_height`  设置为一个很小的数，或为零时，渲染出来就失控了：

```
preset_keyboards:
  default:
    name: 物理鍵盘专用
    author: "osfans <waxaca@163.com>"
    ascii_mode: 0
    width: 10
    height: 0
    keyboard_height: 0
    lock: true #切換程序時記憶鍵盤
    keys:
      - {click: '1'}
      - {click: '2'}
      - {click: '3'}
      - {click: '4'}
      - {click: '5'}
      - {click: '6'}
      - {click: '7'}
      - {click: '8'}
      - {click: '9'}
      - {click: '0'}
  mini:
    name: 精简键盘
    author: "tumuyan"
    ascii_mode: 0
    width: 10
    height: 0
    keyboard_height: 0
    lock: true #切換程序時記憶鍵盤
    keys:
      - {click: '1'}
      - {click: '2'}
      - {click: '3'}
      - {click: '4'}
      - {click: '5'}
      - {click: '6'}
      - {click: '7'}
      - {click: '8'}
      - {click: '9'}
      - {click: '0'}
```

![8D3D419D2BDA00D6B9FB058189FDAB6C](https://github.com/osfans/trime/assets/3107994/053f39e2-0d2c-4d49-a9d6-7bc1b8422d54)

**Comment by WhiredPlanck** [comment]
@yanhuacuo 你是想说，外接物理键盘时，隐藏掉虚拟键盘吗？

**Comment by yanhuacuo** [comment]
> @yanhuacuo 你是想说，外接物理键盘时，隐藏掉虚拟键盘吗？

对，目前不是实现不了嘛，所以就变通着，想想办法，尝试类 mini 键盘这样，定义一个很小或零的数值，让它隐藏掉。
但是，现在实现不了，键面高度设置为零时，就失控了。

**Comment by Freed-Wu** [comment]
> 尝试类 mini 键盘这样，定义一个很小或零的数值，让它隐藏掉。

我參考 https://github.com/osfans/trime/issues/1058 

`/sdcard/rime/trime.default.yaml`:

```yaml
---
patch:
  preset_keyboards/mini/height: 1
  preset_keyboards/mini/keyboard_height: 2
  preset_keyboards/mini/keys: []
```

![Screenshot_20240222_205226_org mozilla fenix](https://github.com/osfans/trime/assets/32936898/8bf57b03-0036-4d20-9f2f-99a1ff030319)

数字再调小就不行了
