### ISSUE TITLE
唤出键盘时无法自动匹配相应布局，必须更改一次输入方案

### ISSUE THREAD

**Issue by Wenti-D** [osfans/trime#1259]
**Describe the bug**
唤出键盘时无法自动匹配相应布局，必须更改一次输入方案才能重新正确匹配。
而按下回车后正确匹配的又变成初始的了。

**To Reproduce**
1. 换到一个可以打字的地方；
2. 唤出键盘，我打微软双拼，得有分号，但默认出来的布局是我自己主题的 36 键默认布局，没有分号。

**Expected behavior**
唤出键盘时应能够自动匹配相应布局。

**Log**
[com.osfans.trime-2024-02-18T16_53_35Z.txt](https://github.com/osfans/trime/files/14323537/com.osfans.trime-2024-02-18T16_53_35Z.txt)

**Screenshots**
https://github.com/osfans/trime/assets/73067578/2938d18a-a2cb-4d53-9d4d-478ae390be05

**Smartphone (please complete the following information):**
 - Device: HUAWEI P40 Pro
 - OS: Harmony OS 4（Android 12 兼容）
 - Theme: [星天](https://github.com/Wenti-D/Astralwelkin)
 - Version: 3.2.17 beta-1 36
 - Build info: 
   ```
   构建者：Windy Deng
   Git 仓库： https://github.com/osfans/trime.git
   构建 Git 哈希：c5ff32480d901210a9ff36f7ef4c4311e0936f9e
   构建时间：2024 年 2 月 19 日 00:32:25
   ```
**Additional context**
默认 trime 主题键盘全有分号，没法确定是否影响。

**Comment by nopdan** [comment]
你得让程序知道你要用到分号。
```yaml
# <schema_id>.schema.yaml
speller:
  alphabet: "abcdefghijklmnopqrstuvwxyz;"
```
这会自动匹配主题中的 qwerty_ 键盘。

如果想用你自定义的键盘，需要修改主题 
```yaml
# *.trime.yaml
preset_keyboards:
  <schema_id>:
    import_preset: <keyboard_id>
```
