### ISSUE TITLE
[question] How to toggle option by hot key

### ISSUE THREAD

**Issue by Freed-Wu** [osfans/trime#1268]
According to https://github.com/osfans/trime/wiki/trime.yaml-%E8%A9%B3%E8%A7%A3

```yaml
#xxx.schema.yaml

switches:

  # 这个按键用来切换键盘布局（在主键盘、数字键盘、英文键盘之间轮换）
  - options: [_keyboard_.default, _keyboard_number, _keyboard_letter]
    states: [默认, 123, abc]
  #多个键盘轮换的功能还有一些问题，有待完善
```

How can we toggle options by hotkey?

I try

`double_pinyin_mspy.custom.yaml`:

```yaml
patch:
  __include: emoji_suggestion:/patch
  switches/@before 0:
    name: keyboard
    reset: 0
    options:
      - _keyboard_.default
      - _keyboard_XXX
    states:
      - XXX
      - YYY
```

`default.custom.yaml`:

```yaml
patch:
  key_binder/bindings/@before 6:
    accept: Control+1
    toggle: keyboard
    when: always
```

and I expect press <kbd>Ctrl</kbd> + <kbd>1</kbd> can toggle keyboard, but it cannot work.

TIA!
