### ISSUE TITLE
[docs] Any document about liquid_keyboard

### ISSUE THREAD

**Issue by Freed-Wu** [osfans/trime#1269]
I search clipboard and draft, as a result, I found they seem to be related to liquid_keyboard. However I cannot find any document about liquid_keyboard in https://github.com/osfans/trime/wiki/trime.yaml-%E8%A9%B3%E8%A7%A3

Can I have

```yaml
switches:
  # 这个按键用来切换键盘布局（在主键盘、数字键盘、英文键盘之间轮换）
  - options: [_keyboard_.default, _keyboard_number, _keyboard_letter, _keyboard_clipboard]
    states: [默认, 123, abc, clipboard]
```

?

**Comment by goofyz** [comment]
Yes, you can.

In `trime.yaml`, there are `preset_keys` like `liquid_keyboard_emoji` and `liquid_keyboard_emoji`.  You can add them to switch like

```
  - options: [_key_liquid_keyboard_emoji, liquid_keyboard_clipboard,_keyboard_mini]
    states: ["😃️", "CLIP", "🎹"]
```

You can add a custom key to `preset_keys` as well.

**Comment by Freed-Wu** [comment]
I try however it cannot work for me :cry: :

`double_pinyin_mspy.custom.yaml`:

```yaml
---
patch:
  __include: emoji_suggestion:/patch
  switches/@before 0:
    name: keyboard
    reset: 0
    options:
      - _keyboard_.default
      - liquid_keyboard_clipboard
      - liquid_keyboard_draft
      - _keyboard_kao_happy
    states:
      - "⌨️\uFE0E"
      - 📋
      - 📝
      - ^_^
```

![Screenshot_20240226_150413](https://github.com/osfans/trime/assets/32936898/88d1de03-9a2f-48bc-9f40-504d56c01f35)

The keyboard still be mini (connected bluetooth keyboard) not clipboard.
