### ISSUE TITLE
[question] How to change ascii_mode temporarily in kaomoji keyboard?

### ISSUE THREAD

**Issue by Freed-Wu** [osfans/trime#1272]
![Screenshot_2024-02-26-13-58-35-90_984e1414ae90666a90f12ff17ec14a7f_025112](https://github.com/osfans/trime/assets/32936898/08b8e9ca-7748-4499-b515-f5264b21dc2d)

When ascii_mode is Chinese, `^` will be mapper to `……` , `_` will be mapper to `——`.

**Describe the solution you'd like**
Change ascii_mode to English, input kaomoji `^_^`, the change it to original ascii_mode.

**Comment by shitlime** [comment]
Use `ascii_mode: 1` and `reset_ascii_mode: true` in the kaomoji preset keyboards.

^ω^

**Comment by Freed-Wu** [comment]
I try however it cannot work for me. This is `/sdcard/rime/build/tongwenfeng.trime.yaml`:

```yaml
preset_keyboards:
  kao_happy:
    ascii_mode: 1
    author: llx
    height: 24
    keys: [{click: "^_^", key_text_size: 14}, {click: "^ω^", key_text_size: 14}, {click: "^o^", key_text_size: 14}, {click: "~\\(≧▽≦)/~", key_text_size: 14}, {click: "*^_^*", key_text_size: 14}, {click: "↖(^ω^)↗", key_text_size: 14}, {click: "(^o^)／", key_text_size: 14}, {click: "(=^▽^=)", key_text_size: 14}, {click: "=^_^=", key_text_size: 14}, {click: "(*^ω^*)", key_text_size: 14}, {click: "٩(๑^o^๑)۶", key_text_size: 14}, {click: "o(￣▽￣)o", key_text_size: 14}, {click: "Y(^_^)Y", key_text_size: 14}, {click: "٩( 'ω' )و", key_text_size: 14}, {click: "╰(*´︶`*)╯", key_text_size: 14}, {click: "*罒▽罒*", key_text_size: 14}, {click: "ヾ ^_^♪", key_text_size: 14}, {click: "=￣ω￣=", key_text_size: 14}, {click: "︿(￣︶￣)︿", key_text_size: 14}, {click: "(´▽｀)ノ♪", key_text_size: 14}, {click: "乁( ˙ ω˙乁)", key_text_size: 14}, {click: "✧*｡٩(ˊωˋ*)و✧*｡", key_text_size: 10}, {click: "～(￣▽￣～)(～￣▽￣)～", key_text_size: 14, width: 50}, {click: Keyboard_default, height: 24, key_back_color: benter, key_text_color: tenter, key_text_size: 16, width: 12.5}, {click: Keyboard_kaoh, key_back_color: benter, key_text_color: tenter, key_text_size: 16, width: 12.5}, {click: Keyboard_kaof, key_back_color: bgn, key_text_color: tgn, key_text_size: 16, width: 12.5}, {click: Keyboard_kaoa, key_back_color: bgn, key_text_color: tgn, key_text_size: 16, width: 12.5}, {click: Keyboard_kaoi, key_back_color: bgn, key_text_color: tgn, key_text_size: 16, width: 12.5}, {click: Keyboard_kaos, key_back_color: bgn, key_text_color: tgn, key_text_size: 16, width: 12.5}, {click: Keyboard_kaom, key_back_color: bgn, key_text_color: tgn, key_text_size: 16, width: 12.5}, {click: BackSpace, key_back_color: benter, key_text_color: tenter, key_text_size: 16, width: 12.5}]
    name: "颜文字键盘-开心"
    reset_ascii_mode: true
    width: 25
```
