### ISSUE TITLE
一个dvorak键盘布局

### ISSUE THREAD

**Issue by xcheny** [osfans/trime#132]
有esc, tab和`shift`, 希望加到程序里.
```
    dvorakv:
        ascii_mode: 0
        author: "xcheny"
        height: 44
        keys: [{click: "`", long_click: "~"}, {click: 1, long_click: "!"}, {click: 2, long_click: "@"}, {click: 3, long_click: "#"}, {click: 4, long_click: "$"}, {click: 5, long_click: "%"}, {click: 6, long_click: "^"}, {click: 7, long_click: "&"}, {click: 8, long_click: "*"}, {click: 9, long_click: "("}, {click: 0, long_click: ")"}, {click: Escape, width: 10}, {click: "'", long_click: "\""}, {click: ",", long_click: "<"}, {click: ., long_click: ">"}, {click: p, long_click: paste}, {click: y, long_click: copy}, {click: f, long_click: "["}, {click: g, long_click: "]"}, {click: c, long_click: cut}, {click: r, long_click: "="}, {click: l, long_click: Right}, {click: Tab, width: 10}, {click: a, long_click: select_all}, {click: o, long_click: "√"}, {click: e, long_click: "|"}, {click: u, long_click: "\\"}, {click: i, long_click: Insert}, {click: d, long_click: Delete}, {click: h, long_click: Left}, {click: t, long_click: "{"}, {click: n, long_click: "}"}, {click: s, long_click: Page_Up}, {click: Shift_L, width: 10}, {click: ";", long_click: ":"}, {click: q, long_click: "±"}, {click: j, long_click: Down}, {click: k, long_click: Up}, {click: x, long_click: "-"}, {click: b, long_click: _}, {click: m, long_click: "+"}, {click: w, long_click: Home}, {click: v, long_click: End}, {click: z, long_click: Page_Down}, {click: Keyboard_symbols, long_click: Keyboard_number}, {click: Mode_switch, long_click: Menu}, {click: BackSpace, width: 15}, {click: "/", long_click: "?"}, {click: space, width: 32}, {click: Return, long_click: CommitComment, width: 26}]
        name: "dvorak50鍵"
        width: 9
```

**Comment by xcheny** [comment]
```
dvorakv:
    ascii_mode: 0
    author: xcheny
    height: 44
    keys: [{click: "`", long_click: "~"}, {click: 1, long_click: "!"}, {click: 2, long_click: "@"}, {click: 3, long_click: "#"}, {click: 4, long_click: "$"}, {click: 5, long_click: "%"}, {click: 6, long_click: "^"}, {click: 7, long_click: "&"}, {click: 8, long_click: "*"}, {click: 9, long_click: "("}, {click: 0, long_click: ")"}, {click: Escape, width: 10}, {click: "'", long_click: "\""}, {click: ",", long_click: "<"}, {click: ., long_click: ">"}, {click: p, long_click: paste}, {click: y, long_click: copy}, {click: f, long_click: "["}, {click: g, long_click: "]"}, {click: c, long_click: cut}, {click: r, long_click: "="}, {click: l, long_click: Right}, {click: Tab, width: 10}, {click: a, long_click: select_all}, {click: o, long_click: "√"}, {click: e, long_click: "|"}, {click: u, long_click: "\\"}, {click: i, long_click: Insert}, {click: d, long_click: Delete}, {click: h, long_click: Left}, {click: t, long_click: "{"}, {click: n, long_click: "}"}, {click: s, long_click: Page_Up}, {click: Shift_L, width: 10}, {click: ";", long_click: ":"}, {click: q, long_click: "±"}, {click: j, long_click: Down}, {click: k, long_click: Up}, {click: x, long_click: "-"}, {click: b, long_click: _}, {click: m, long_click: "+"}, {click: w, long_click: Home}, {click: v, long_click: End}, {click: z, long_click: Page_Down}, {click: Keyboard_symbols, long_click: Keyboard_number}, {click: Mode_switch, long_click: Menu}, {click: BackSpace, width: 15}, {click: "/", long_click: "?"}, {click: space, width: 32}, {click: Return, long_click: CommitComment, width: 26}]
    name: "dvorak50鍵"
    width: 9
```
issue能修改吗? 刚才没发好.
