### ISSUE TITLE
按键行间距 vertical_gap 不生效

### ISSUE THREAD

**Issue by Urie96** [osfans/trime#1438]
### 摘要 / Summary

在trime.custom.yaml里配置了
```yaml
patch:
  'style/horizontal_gap': 4
  'style/vertical_gap': 8
  'style/round_corner': 16
```
但是好像实际生效的是0，我看trime.yaml里面也是1啊。（调整trime.custom.yaml的horizontal_gap是生效的）

### 重现步骤 / Steps to Reproduce

如上

### 预期行为 / Expected Behavior

按键有一定的行间距

### 截图 / Screenshot

![1331722138787_ pic](https://github.com/user-attachments/assets/eb368662-bfba-4cb8-b103-82f2c901df33)

### 系统版本 / OS Version

安卓14

### 应用版本 / App Version

v3.2.19-0-ge46046ab-release

### 构建信息 / Build Information

构建者：F-Droid
Git 仓库：https://github.com/osfans/trime
构建 Git 哈希：e46046abfb030a2687033f74ad00d1b2693af433
构建时间：2024年7月3日 08:17:08
