### ISSUE TITLE
花园明朝B字体与默认候选字体不兼容

### ISSUE THREAD

**Issue by iLJaXn** [osfans/trime#1468]
### 摘要 / Summary

使用tongwenfeng.trime.custom.yaml设定HanaMinB.tff为主题的候选扩展字体，此前使用`3.2.x`版本可以正常显示拓展字体，但更新至`f-droid`最新稳定版`3.3.0`后， 仅设置花园明朝b作为扩展字体时不显示，但若同时设置花园明朝a作为候选字体，则扩展字体也显示正常显示。更新至每夜版后亦未解决。

### 重现步骤 / Steps to Reproduce

tongwenfeng.trime.custom.yaml
```yaml
patch:                                                  
  #"style/candidate_font": HanaMinA.ttf                  
  "style/hanb_font": HanaMinB.ttf                      
  "style/candidate_text_size": 24                       
  "style/candidate_view_height": 28                     
  "style/candidate_padding": 8                          
  "style/text_size": 18
```

### 预期行为 / Expected Behavior

23年5月时稳定版本的显示效果截图：
![Screenshot_20240919_211542](https://github.com/user-attachments/assets/569c1104-7fb7-48e8-ac9c-16b7761f8164)

### 日志 / Log

```plain
--------- Device Info
OS Name: ALN-AL80 4.2.0.135(SP3C01E100R5P16)
OS Version: 5.10.43 (104.2.0.135SP3C01)
OS API Level: 31
Device: HWALN
Model (product): ALN-AL80 (ALN-AL80)
Manufacturer: HUAWEI
Tags: release-keys
Screen Size: 1260 x 2590
Screen Density: 3.25
Screen orientation: Portrait
--------- Build Info
Package Name: com.osfans.trime
Builder: Nightly CI
Version Code: 20241101
Version Name: nightly-2-gfe9c39dc-release
Build Time: 2024-09-18T16:06:36Z
Build Git Hash: fe9c39dc41d8c8d9596aded56b158e67659abb2c
09-19 21:22:06.955 E/OpenGLRenderer(20471): Unable to match the desired swap behavior.
09-19 21:22:07.602 E/InputTransport(20471): now=56156930439868, frameTime=56156930367472, sampleTime=56156925367472, firstPointTime=56156927349000, batchSize=1
09-19 21:22:07.760 E/OpenGLRenderer(20471): Unable to match the desired swap behavior.
09-19 21:22:07.807 E/InputTransport(20471): now=56157135224764, frameTime=56157134933522, sampleTime=56157129933522, firstPointTime=56157130711000, batchSize=1
09-19 21:22:07.950 E/OpenGLRenderer(20471): Unable to match the desired swap behavior.
09-19 21:22:08.095 E/OpenGLRenderer(20471): Unable to match the desired swap behavior.
09-19 21:22:08.212 E/OpenGLRenderer(20471): Unable to match the desired swap behavior.
09-19 21:22:09.730 E/OpenGLRenderer(20471): Unable to match the desired swap behavior.
09-19 21:22:17.462 E/OpenGLRenderer(20471): Unable to match the desired swap behavior.
```

### 截图 / Screenshot

启用花园明朝b作为扩展字体时：
![Screenshot_20240919_210344](https://github.com/user-attachments/assets/9ae35fee-a2b5-49d6-83de-c3cf7f15472a)
同时启用花园明朝a作为候选字体：
![Screenshot_20240919_210538](https://github.com/user-attachments/assets/9629a225-008b-4dd0-86a1-edff82e9e4ab)
仅启用花园明朝a作为候选字体时：
![Screenshot_20240919_210716](https://github.com/user-attachments/assets/363a96e7-735e-4f65-b02f-c994caa545db)

### 附加信息 / Additional Context

正常设置与部署，字体文件位于rime/fonts文件夹中，输入法schema中未指定候选字体

### 系统版本 / OS Version

HarmonyOS 4.2.0

### 应用版本 / App Version

nightly-2-gfe9c39dc-release

### 构建信息 / Build Information

```
构建者：Nightly CI
Git 仓库：https://github.com/osfans/trime
构建 Git 哈希：fe9c39dc41d8c8d9596aded56b158e67659abb2c
构建时间：2024年9月19日 00:06:36
```

**Comment by WhiredPlanck** [comment]
字体设置现支持列表格式：

```yaml
style:
  candidate_font:
    - a.ttf
    - b.ttf
    - ...
```

配置字体后会按照列表的顺序优先级尝试显示字体，当 a 字体无法显示某个字时，会尝试用 b 字体来显示这个字。以此类推。
