### ISSUE TITLE
`style/keyboard_height_land` 选项没有作用

### ISSUE THREAD

**Issue by UlyssesZh** [osfans/trime#1472]
### 摘要 / Summary

`style/keyboard_height_land` 选项没有作用, 只有 `style/keyboard_height` 有作用. 也就是说, 横屏时的键盘高度一直与竖屏时的一致.

### 重现步骤 / Steps to Reproduce

在 tongwenfeng.trime.custom.yaml 中写

```yaml
patch:
  style/keyboard_height: 280
  style/keyboard_height_land: 190
```

将主题切换为 tongwenfeng. 重新部署. 发现不管横屏还是竖屏, 高度都是 280.

### 预期行为 / Expected Behavior

竖屏时键盘高度为 280, 横屏是键盘高度为 190.

### 日志 / Log

无有用信息.

### 系统版本 / OS Version

Android 11

### 应用版本 / App Version

3.3.0

### 构建信息 / Build Information

Builder: F-Droid
Git Repo: https://github.com/osfans/trime
Build Git Hash: 436c8fc42af638fdd8744533beec03567ec03c6c
Build Time: Sep 8, 2024 03:18:51
