### ISSUE TITLE
实体键盘如何适配？

### ISSUE THREAD

**Issue by cccooogit** [osfans/trime#151]
新买了一个二手全键盘手机作备机，装了最新发布版，能切换到实体键盘输入状态，但有以下问题：
1，shift键，alt键不起作用；
2，sym键出大写Y字符，！键出大写X字符。
请问能否通过配置文件修改实体按键与字符映射关系？

百度输入法可修改系统/system/usr/keylayout/中kl后缀文件和应用自己的ini键盘映射文件解决，同文输入法是否也类似？
此类问题解决方案应该对于适配实体键盘有共性。
另：全键盘手机型号是三星b5330

**Comment by osfans** [comment]
kl肯定是可以改的，安卓通用的。

**Comment by cccooogit** [comment]
root了应用百度的kl文件，sym不起作用，！键出@字符，同时按shift或alt键能出主键之上的字符，如一般标准实体键盘，但不能象软键盘那样单手点一下，再点一下出主键之上字符。
同文输入法能修改键盘映射关系吗？
黑莓priv或keyone的用户用同文也是这样？

**Comment by osfans** [comment]
嗯，目前組合鍵都有些問題。

**Comment by osfans** [comment]
其他輸入法都不用改的話，應該等組合鍵好了就正常了。

**Comment by freeyoung** [comment]
KeyOne 用户在此，Sym, Alt, Shift 无作用，不过这个对我来说不是特别大的问题，我想解决的是 Z Y 倒置问题，我因为地理位置原因，购买的是德语键盘版本，在 Mac 上修改 schema 的 key_binder 可以解决倒置，但在同文下就不可以了，请问是我的修改方法有问题还是同文暂不支持硬键盘重映射？

```
key_binder:
  import_preset: default
  bindings:
    - accept: y
      send: z
      when: always
    - accept: z
      send: y
      when: always
```
