### ISSUE TITLE
加入五笔繁体

### ISSUE THREAD

**Issue by mimimicx7** [osfans/trime#154]
安卓系统可以在下次版本更新直接加入五笔简入繁出吗?谢谢

**Comment by osfans** [comment]
這個還是自己定製吧，放在/sdcard/rime裏面。
以後倒是想做在線下載方案。

**Comment by mimimicx7** [comment]
说真的,我以前s5简入繁出能成功.现在换手机s8了同样的设置新手机打不了繁体.文科生出身的我真不知道问题出在哪里,只好厚着脸皮来这里求教了.毕竟这是我用过最好的输入法.非常感谢.

**Comment by osfans** [comment]
基本上加上simplifier就好。我來找個示例。

**Comment by osfans** [comment]
加engine/filters：
https://github.com/rime/rime-luna-pinyin/blob/master/luna_pinyin_tw.schema.yaml#L46

加上simplifier：
https://github.com/rime/rime-luna-pinyin/blob/master/luna_pinyin_tw.schema.yaml#L83
要簡體轉繁體的話，opencc_config可以修改成：
s2hk.json、s2t.json、s2tw.json、s2twp.json

加switches，如果要手動切換的話，需加上states: [簡體, 繁體]：
https://github.com/rime/rime-luna-pinyin/blob/master/luna_pinyin_tw.schema.yaml#L21

所以總共就這三處：
```yaml

switches:
  - name: zh_tw
    states: [簡體, 繁體]
    reset: 1 #默認繁體

engine:
  filters:
    - simplifier
    - uniquifier

simplifier:
  opencc_config: s2tw.json #還可以是s2hk.json、s2t.json、s2tw.json、s2twp.json
  option_name: zh_tw #跟switches中的name要一致
```
