### ISSUE TITLE
模仿五笔双键教程，无法实现双键键盘

### ISSUE THREAD

**Issue by dddog999** [osfans/trime#208]
如题，想在手机上用用山人输入法，按照ｗｉｋｉ的教程实现了模糊音，但第四步双键键盘不能实现，请教各位，如何是好？

```
#trime.custom.yaml
patch:
  #1、新建一個按鍵佈局wubi86_double_key
  "preset_keyboards/sunman2k:  #佈局ID
    author: "dddog"   #作者
    name: "山人通用2k"  #方便自己辨識的名字
    ascii_mode: 0 #默認進入中文狀態
    height: 60   #每行高度
    width: 20   #按鍵默認寬度（取所有按鍵中用得較多的寬度值，接下來就可以少寫一些width了） 
    keys:   #按鍵排列
      #第一行
      - {label: "Q W", click: q, long_click: 1}
      - {label: "E R", click: e, long_click: 2}
      - {label: "T Y", click: t, long_click: 3}
      - {label: "U I", click: u, long_click: 4}
      - {label: "O P", click: o, long_click: 5}
 
      #第二行
      - {label: "A S", click: a, long_click: 6}
      - {label: "D F", click: d, long_click: 7}
      - {label: "G H", click: g, long_click: 8}
      - {label: "J K", click: j, long_click: 9}
      - {label: "L"  , click: l, long_click: 0}
 
      #第三行
      - {label: "查" , click: `, width: 10}
      - {label: "Z"  , click: z, long_click: "@", width: 10}
      - {label: "X C", click: x, long_click: "!"}
      - {label: "V B", click: v, long_click: "?"}
      - {label: "N M", click: n, long_click: "."}
      - {click: BackSpace}
 
      #第四行
      - {click: Keyboard_symbols, width: 15}
      - {click: Keyboard_qwerty, label: "全", long_click: Menu, width: 10}
      - {click: "，", width: 10}
      - {label: " " , click: space, long_click: VOICE_ASSIST, width: 30}
      - {click: "。", width: 10}
      - {label: "123", click: Keyboard_number, width: 10}
      - {label: "确定", click: Return, width: 15}
 
  "style/keyboards":
    - .default
    - default
    - number
    - symbols
    - qwerty
 
  "preset_keyboards/qwerty/ascii_mode": 1
 
  "style/candidate_view_height": 36
  "style/round_corner": 0.0
  "style/label_text_size": 18
  "style/comment_height": 14
  "preset_keys/Keyboard_defaultw":   #返回中文键盘
      label: 英
      select: .default
      send: Eisu_toggle
  "preset_keys/space":
    functional: false
    label: " "
    repeatable: false  #关掉空格键重复
    send: space

```

```
custom_phrase:
  db_class: stabledb
  dictionary: ""
  enable_completion: false
  enable_sentence: false
  initial_quality: 0
  user_dict: custom_phrase
customization: 1884868771
engine:
  filters:
    - simplifier
    - uniquifier
    - "reverse_lookup_filter@pinyin_reverse_lookup"
    - "reverse_lookup_filter@jyutping_reverse_lookup"
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - "affix_segmentor@pinyin"
    - "affix_segmentor@jyutping"
    - "affix_segmentor@pinyin_lookup"
    - "affix_segmentor@reverse_lookup"
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - script_translator
    - "script_translator@pinyin"
    - "script_translator@jyutping"
    - "script_translator@pinyin_lookup"
    - "script_translator@jyutping_lookup"
    - reverse_lookup_translator
    - "table_translator@custom_phrase"
jyutping:
  closing_tips: "【山人】"
  dictionary: jyutping
  enable_charset_filter: true
  initial_quality: 0.1
  prefix: J
  suffix: ";"
  tag: jyutping
  tips: "【粵拼】"
jyutping_lookup:
  closing_tips: "【山人】"
  dictionary: jyutping
  prefix: "`J"
  suffix: ";"
  tag: jyutping_lookup
  tips: "【粵拼反查】"
jyutping_reverse_lookup:
  dictionary: sunman.extended
  overwrite_comment: true
  tags:
    - jyutping_lookup
key_binder:
  import_preset: default
menu:
  page_size: 9
pinyin:
  closing_tips: "【山人】"
  dictionary: pinyin_simp
  enable_charset_filter: true
  initial_quality: 0.2
  preedit_format:
    - "xform/([nl])v/$1ü/"
    - "xform/([nl])ue/$1üe/"
    - "xform/([jqxy])v/$1u/"
  prefix: P
  suffix: ";"
  tag: pinyin
  tips: "【拼音】"
pinyin_lookup:
  closing_tips: "【山人】"
  dictionary: pinyin_simp
  preedit_format:
    - "xform/([nl])v/$1ü/"
    - "xform/([nl])ue/$1üe/"
    - "xform/([jqxy])v/$1u/"
  prefix: "`P"
  suffix: ";"
  tag: pinyin_lookup
  tips: "【拼音反查】"
pinyin_reverse_lookup:
  dictionary: sunman.extended
  overwrite_comment: true
  spelling_hints: true
  tags:
    - pinyin_lookup
punctuator:
  import_preset: symbols
recognizer:
  import_preset: default
  patterns:
    jyutping: "(?<!`)J[a-z']*;?$"
    jyutping_lookup: "`J[a-z]*;?$"
    pinyin: "(?<!`)P[a-z']*;?$"
    pinyin_lookup: "`P[a-z]*;?$"
    punct: "^/[0-9]?[a-z]*$"
    reverse_lookup: "`[a-z]*;?$"
reverse_lookup:
  closing_tips: "【拼音】"
  extra_tags:
    - pinyin_lookup
    - jyutping_lookup
  prefix: "`"
  suffix: ";"
  tag: reverse_lookup
  tips: "【反查】"
schema:
  author:
    - "谢振斌"
  dependencies:
    - pinyin_simp
    - luna_pinyin
    - jyutping
  description: |
    山人全息码
    sunman.uueasy.com
    
  name: "山人通用2k"
  schema_id: sunman2k
  version: 0.9.custom.1884868771
simplifier:
  option_name: sunman_simp
  tips: all
speller:
  algebra:
    - "fuzz/^(\\w)(\\w).+$/$1$2/"
    - "fuzz/^(\\w)(\\w)(\\w).+$/$1$2$3/"
    - "fuzz/^(\\w)(\\w)(\\w)(\\w).+$/$1$2$3$4/"
    - derive/w/q/
    - derive/r/e/
    - derive/y/t/
    - derive/i/u/
    - derive/p/o/
 
    - derive/s/a/
    - derive/f/d/
    - derive/h/g/
    - derive/k/j/
 
    - derive/c/x/
    - derive/b/v/
    - derive/m/n/
  alphabet: zyxwvutsrqponmlkjihgfedcba
  delimiter: " '"
style:
  horizontal: false
switches:
  - name: ascii_mode
    reset: 0
    states: ["中文", "西文"]
  - name: full_shape
    states: ["半角", "全角"]
  - name: ascii_punct
    states: ["。，", "．，"]
  - name: sunman_simp
    states: ["漢字", "汉字"]
translator:
  dictionary: sunman.extended
  enable_user_dict: true
  prism: sunman2k
  strict_spelling: true

```
