### ISSUE TITLE
符号中的更多怎么用啊？

### ISSUE THREAD

**Issue by NineFox1988** [osfans/trime#215]

**Comment by NineFox1988** [comment]
比如点击符号，更多，几何
效果是/jh
并没有符号界面出现。

**Comment by Prcuvu** [comment]
在用户文件夹中的“`[方案 ID].custom.yaml`”（没有的话请新建）中加入：
```yaml
patch:
  "punctuator/import_preset": symbols
  "recognizer/patterns/punct": "^/([a-z]+|[0-9])$"
```
保存，重新部署。
