### ISSUE TITLE
Ctrl Alt Esc 应该如何配置？

### ISSUE THREAD

**Issue by Henry-T** [osfans/trime#242]
> 版本: v3.0.1-229-g20f5817-20171218

我想把这几个键加入我的Theme，配置如下: 
```yaml
- {click: Control_L, label: "Ct"}
- {click: Alt_L, label: "Al"}
- {click: Esc, label: "Es" send: escape}
...
Control_L: {label: Ct, send: Control_L}
Alt_L: {label: Al, send: Alt_L}
```

但是: 
- Ctrl 和 Alt 没有效果
- Escape 则会直接把键盘隐藏

请问应该如何配置呢？
