### ISSUE TITLE
關於候選字

### ISSUE THREAD

**Issue by philipposkhos** [osfans/trime#341]
想請問一下 candidate_text_size: 候选字大小 /  candidate_view_height: 候选区高度 這兩個在 trime.yaml 的參數現在修改是否有用? 我試過直接修改，或者在 trime.custom.yaml 裡面改，好像都沒有效果

另外，如果候選字左邊有數字，例如1.什 2.午 ，和電腦一樣的效果，現在可以實現嗎?

麻煩了

**Comment by samuel-k-hu** [comment]
你好，我今天试用了同文输入法，发现了和你一样的问题， `trime.custom.yaml` 对于外观的修改不起作用。我主要是想给[给键盘添加删词功能](https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3#%E7%A4%BA%E4%BE%8B%E7%BB%99%E9%94%AE%E7%9B%98%E6%B7%BB%E5%8A%A0%E5%88%A0%E8%AF%8D%E5%8A%9F%E8%83%BD)，并[修改按键间距](https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3#%E7%A4%BA%E4%BE%8B%E5%B1%80%E9%83%A8%E5%B0%BA%E5%AF%B8%E5%BE%AE%E8%B0%83)。

后来我发现，**在主题设置中，将主题由「同文风」改为「默认」，就可以使 `trime.custom.yaml` 的修改生效了。** 以下是我修改后的效果。


![img](https://user-images.githubusercontent.com/38934286/78789853-4a099a80-79e0-11ea-861c-e2d0c2dd4c57.jpg)

**Comment by philipposkhos** [comment]
你好 謝謝回覆

我的情況有點不同，我主題已經是默認了，所以整個鍵盤佈局都有生效。但是關於候選字改動，或者是字體字型都沒有反映，我是直接改trime.yaml 的，custom 那個試了也一樣不行。不知大家有沒有成功修改候選欄的經驗？

**Comment by philipposkhos** [comment]
> 你好，我今天试用了同文输入法，发现了和你一样的问题， `trime.custom.yaml` 对于外观的修改不起作用。我主要是想给[给键盘添加删词功能](https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3#%E7%A4%BA%E4%BE%8B%E7%BB%99%E9%94%AE%E7%9B%98%E6%B7%BB%E5%8A%A0%E5%88%A0%E8%AF%8D%E5%8A%9F%E8%83%BD)，并[修改按键间距](https://github.com/osfans/trime/wiki/trime.yaml%E8%A9%B3%E8%A7%A3#%E7%A4%BA%E4%BE%8B%E5%B1%80%E9%83%A8%E5%B0%BA%E5%AF%B8%E5%BE%AE%E8%B0%83)。
> 
> 后来我发现，**在主题设置中，将主题由「同文风」改为「默认」，就可以使 `trime.custom.yaml` 的修改生效了。** 以下是我修改后的效果。
> 
> ![img](https://user-images.githubusercontent.com/38934286/78789853-4a099a80-79e0-11ea-861c-e2d0c2dd4c57.jpg)

麻煩可以提供一下您 `trime.custom.yaml` 的設置嗎？ 我想參考一下看我是不是弄錯了。

麻煩了

**Comment by samuel-k-hu** [comment]
你好，这是我的配置：

```yaml
customization:
  distribution_code_name: ""
  distribution_version: ""
  generator: "Rime-JNI"
  modified_time: "Thu Sep 17 09:11:24 2015"
  rime_version: 1.2.9
patch:
  "style/locale": zh_CN # 添加为汉语简体
  "style/show_preview": false #按鍵提示
  "style/show_comment": false #顯示提示區
  "style/key_sound": false
  "style/color_scheme": lost_temple
  "style/text_size": 18 #编码字体大小  
  "style/candidate_text_size": 22
  "style/key_text_size": 22 #按键字体大小  
  "style/vertical_gap": 8   # 行距
  "style/horizontal_gap": 6  # 水平间距改为0
  "style/round_corner": 15    # 按键圆角改为0
  # 1、让朙月拼音使用36键键盘布局  
  "preset_keyboards/luna_pinyin/import_preset": qwerty0
  "preset_keyboards/double_pinyin_flypy/import_preset": qwerty0
  # 2、给36键键盘添加方向键和删词键  
  "preset_keyboards/qwerty0/keys/@7/has_menu": Left
  "preset_keyboards/qwerty0/keys/@8/has_menu": Right
  "preset_keyboards/qwerty0/keys/@9/has_menu": DeleteCandidate
```
