### ISSUE TITLE
请问同文输入法如何过滤生僻字？在小狼毫上成功，但同文不成功。

### ISSUE THREAD

**Issue by 4SM** [osfans/trime#374]
```
#double_pinyin_flypy.custom.yaml

  switches:
    - name: ascii_mode
      states: [ 中文, 西文 ]
      reset: 0
    - name: full_shape
      states: [ 半角, 全角 ]
      reset: 0
    - name: simplification
      states: [ 漢字, 汉字 ]
      reset: 1
    - name: ascii_punct
      states: [ 。，, ．， ]
    - options: ["gb2312","utf8"]
      reset: 0
      states: [ 通用, 增廣 ]

  filters:
    - simplifier
    - uniquifier
    - charset_filter@gb2312
```

电脑上过滤掉了生僻字，但手机上的同文却没有被过滤掉。
请问，我哪里做错了吗？或者还需要修改其他配置文件？
万分感谢。
