### ISSUE TITLE
版本3.1.3-20200719中tongwenfeng.trime.yaml 文件的几处小毛病

### ISSUE THREAD

**Issue by arockshan** [osfans/trime#382]
- 第3915与第3916行: 第二行 `Keyboard_bqkj4` 应改为 `Keyboard_bqkj5`

```yaml
Keyboard_bqkj4: {label: 科技4, functional: false, send: Eisu_toggle, select: bqkj4}
Keyboard_bqkj4: {label: 科技5, functional: false, send: Eisu_toggle, select: bqkj5}
```

- 第966行：`{Keyboard_default}` 似应该去掉，不然在输入数字的过程中一输入圆括号()便会跳到主键盘

```yaml
- {click: '(){Left}{Keyboard_default}', long_click: '@', key_back_color: bgn, key_text_color: tgn}
```

- 第73行漏掉的键盘：bqrw6, bqhc3, bqlx6, bqkj5, bqqz6

- 不直接改动 *tongwenfeng.trime.yaml* 文件的话，在 *tongwenfeng.trime.custom.yaml* 文件中加入以下代码可解决相关小毛病：

```yaml
  # 加上漏掉的键盘：bqrw6, bqhc3, bqlx6, bqkj5, bqqz6
  "style/keyboards": [.default, letter, default, number, symbols, edit, move, bqrw1, bqrw2, bqrw3, bqrw4, bqrw5, bqrw6, bqqt1, bqqt2, bqqt3, bqqt4, bqqz1, bqqz2, bqqz3, bqqz4, bqqz5, bqqz6, bqpt1, bqpt2, bqhd1, bqhd2, bqhc1, bqhc2, bqhc3, bqlx1, bqlx2, bqlx3, bqlx4, bqlx5, bqlx6, bqkj1, bqkj2, bqkj3, bqkj4, bqkj5, bqfh1, bqfh2, bqfh3, bqfh4, kao_fond, kao_sad, kao_mad, kao_astonished, kao_impotent, kao_happy, numberb]

  # 重建功能键 Keyboard_bqkj4 与 Keyboard_bqkj5
  "preset_keys/Keyboard_bqkj4": {label: 科技4, functional: false, send: Eisu_toggle, select: bqkj4}
  "preset_keys/Keyboard_bqkj5": {label: 科技5, functional: false, send: Eisu_toggle, select: bqkj5}

  # 数字键盘圆括号调整
  "preset_keyboards/number/keys/@12/click": '(){Left}' 
```
