### ISSUE TITLE
分享对配色的一种简单改造

### ISSUE THREAD

**Issue by arockshan** [osfans/trime#391]
「同文输入法」提供了许多的漂亮的配色方案，但在键盘默认设置下给我个人的观感并不太好，其中主要的问题是：

- 按键的 *颗粒感* 不够
- 众多配色方案都是全键盘一种颜色，在手机上对视觉与打字并不友好

针对这两种个人感受，我的改造尝试是：

- 增大圆角： 比如 `"sytle/round_corner": 30` ； 在不改动按键水平间隙和竖直间隙的条件下，增大圆角可以增加按键四角的间隙，使按键 *一颗一颗的感觉* 更明显，也使边界（border）在整个键盘的占比变大。
- 边界填色： 许多配色的 `border_color` 与 `back_color` 的颜色值相同是键盘看起来铁板一块的原因所在，所以只要给按键的间隙填上色，便能改善这个问题。我的选择是两种不同的灰色。把两种颜色都写上去，是为了便利我在两种灰色间切换；有的方案两种灰色都注释掉，则是因为原有的方案已经足够好。

    ```yaml
    # "preset_color_schemes/azure/border_color": 0xeceff1
    "preset_color_schemes/azure/border_color": 0xd3d7da
    # "preset_color_schemes/luna/border_color": 0xeceff1
    "preset_color_schemes/luna/border_color": 0xd3d7da
    # "preset_color_schemes/ink/border_color": 0xeceff1
    # "preset_color_schemes/ink/border_color": 0xd3d7da
    # "preset_color_schemes/lost_temple/border_color": 0xeceff1
    "preset_color_schemes/lost_temple/border_color": 0xd3d7da
    # "preset_color_schemes/dark_temple/border_color": 0xeceff1
    "preset_color_schemes/dark_temple/border_color": 0xd3d7da
    # "preset_color_schemes/starcraft/border_color": 0xeceff1
    # "preset_color_schemes/starcraft/border_color": 0xd3d7da
    # "preset_color_schemes/solarized_rock/border_color": 0xeceff1
    "preset_color_schemes/solarized_rock/border_color": 0xd3d7da
    "preset_color_schemes/tintin/border_color": 0xeceff1
    # "preset_color_schemes/tintin/border_color": 0xd3d7da
    # "preset_color_schemes/dota_2/border_color": 0xeceff1
    "preset_color_schemes/dota_2/border_color": 0xd3d7da
    "preset_color_schemes/brasil/border_color": 0xeceff1
    # "preset_color_schemes/brasil/border_color": 0xd3d7da
    # "preset_color_schemes/doraemon/border_color": 0xeceff1
    # "preset_color_schemes/doraemon/border_color": 0xd3d7da
    # "preset_color_schemes/espagna/border_color": 0xeceff1
    "preset_color_schemes/espagna/border_color": 0xd3d7da
    "preset_color_schemes/gholabok/border_color": 0xeceff1
    # "preset_color_schemes/gholabok/border_color": 0xd3d7da
    # "preset_color_schemes/kuma_shuzboz/border_color": 0xeceff1
    "preset_color_schemes/kuma_shuzboz/border_color": 0xd3d7da
    # "preset_color_schemes/kuon/border_color": 0xeceff1
    "preset_color_schemes/kuon/border_color": 0xd3d7da
    "preset_color_schemes/macau/border_color": 0xeceff1
    # "preset_color_schemes/macau/border_color": 0xd3d7da
    # "preset_color_schemes/nba/border_color": 0xeceff1
    "preset_color_schemes/nba/border_color": 0xd3d7da
    # "preset_color_schemes/ps4/border_color": 0xeceff1
    "preset_color_schemes/ps4/border_color": 0xd3d7da
    "preset_color_schemes/skype/border_color": 0xeceff1
    # "preset_color_schemes/skype/border_color": 0xd3d7da
    # "preset_color_schemes/xbox_silver/border_color": 0xeceff1
    "preset_color_schemes/xbox_silver/border_color": 0xd3d7da
    "preset_color_schemes/youtube/border_color": 0xeceff1
    # "preset_color_schemes/youtube/border_color": 0xd3d7da
    # "preset_color_schemes/so_young/border_color": 0xeceff1
    # "preset_color_schemes/so_young/border_color": 0xd3d7da
    # "preset_color_schemes/smurfs/border_color": 0xeceff1
    # "preset_color_schemes/smurfs/border_color": 0xd3d7da
    # "preset_color_schemes/wii/border_color": 0xeceff1
    "preset_color_schemes/wii/border_color": 0xd3d7da
    "preset_color_schemes/android/border_color": 0xeceff1
    # "preset_color_schemes/android/border_color": 0xd3d7da
    # "preset_color_schemes/cool_breeze/border_color": 0xeceff1
    "preset_color_schemes/cool_breeze/border_color": 0xd3d7da
    # "preset_color_schemes/google_plus/border_color": 0xeceff1
    # "preset_color_schemes/google_plus/border_color": 0xd3d7da
    # "preset_color_schemes/modern_warfare/border_color": 0xeceff1
    # "preset_color_schemes/modern_warfare/border_color": 0xd3d7da
    # "preset_color_schemes/brisk/border_color": 0xeceff1
    # "preset_color_schemes/brisk/border_color": 0xd3d7da
    # "preset_color_schemes/starcraft_ii/border_color": 0xeceff1
    # "preset_color_schemes/starcraft_ii/border_color": 0xd3d7da
    "preset_color_schemes/steam/border_color": 0xeceff1
    # "preset_color_schemes/steam/border_color": 0xd3d7da
    "preset_color_schemes/flypy/border_color": 0xeceff1
    # "preset_color_schemes/flypy/border_color": 0xd3d7da
    "preset_color_schemes/tantsing/border_color": 0xeceff1
    # "preset_color_schemes/tantsing/border_color": 0xd3d7da
    # "preset_color_schemes/yygc/border_color": 0xeceff1
    "preset_color_schemes/yygc/border_color": 0xd3d7da
    ```
