### ISSUE TITLE
ascii_mode 无效？

### ISSUE THREAD

**Issue by ivysrono** [osfans/trime#405]
```
app_options:
  # Windows
  pwsh.exe:
    ascii_mode: true
  # Android
  net.nhiroki.bluelineconsole:
    ascii_mode: true
```
以上配置在Windows上是有效的，但在Android，我想让 [Blue Line Console](https://f-droid.org/packages/net.nhiroki.bluelineconsole/) 默认英文，似乎无效。
Android11
[Trime | F-Droid - Free and Open Source Android App Repository](https://f-droid.org/packages/com.osfans.trime/)
