### ISSUE TITLE
按键振动问题和导航栏颜色适配

### ISSUE THREAD

**Issue by coxde** [osfans/trime#439]
开发者您好，首先感谢你们无私开发这款软件。

我目前正在使用 3.2.1 版本的 trime，发现在「输入设置」中调整「按键振动强度」，0—255 的实际振动强度都基本一样。而使用 trime.custom.yaml 也无效果，软件只会遵从设置，例如「输入设置」中「按键时振动」为关，则此 patch 就不会生效。

```yaml
patch:
  style/key_vibrate: true
  style/key_vibrate_duration: 1
  style/key_vibrate_amplitude: 1
```

不知道这是软件问题还是仅我个体问题？望解答，谢谢！

此外，我还想请问开发者能否加入「导航栏颜色适配」功能？比如 Gboard 主题颜色改变则键盘下的导航栏颜色也会相匹配，而 trime 则是统一的纯黑色，视觉上不太美观。

![图片](https://user-images.githubusercontent.com/63153334/123507660-2aba6400-d69d-11eb-8b65-91b31f66f8e8.png)
