### ISSUE TITLE
新版蒼頡六代的詞典閃退

### ISSUE THREAD

**Issue by frank-king** [osfans/trime#44]
求解

**Comment by osfans** [comment]
有什麼錯誤信息？華爲沒有抓log的工具話，可以下載一個第三方的看看。懷疑是因爲APK不完整。

**Comment by frank-king** [comment]
就是點安裝後，直接顯示「應用程式未安裝」。

**Comment by frank-king** [comment]
同文平臺能裝上，但就是輸入法用不了

**Comment by frank-king** [comment]
可以用了

**Comment by frank-king** [comment]
但是安裝了最新的版本老是閃退

**Comment by osfans** [comment]
菜單裏回廠trime.yaml和trime.custom.yaml看看。

**Comment by frank-king** [comment]
就是回廠了也閃退呢，20151223以後的版本不行了。現在將就用着20151223的版本。
請問怎樣增加候選關鍵字的個數呢？有時涉及符號的輸入，每頁只有5個候選詞選起來有點慢。
另外，不知道有沒有鍵位修正的功能呢？有時鍵位有偏差，打出來的字就差得很遠。

**Comment by xiaoqun2016** [comment]
（贴吧网页版出故障了，无法回复，我就在这里对容错补充一下。）
后来又观察了一下，轻松仓颉实际也不轻松。如果每次击键 都偏离按键中心，打到第四码的时候就会有明显的卡顿，第五码更是会延迟两三秒。估计是容错产生了很多的编码组合，使要检索的范围成倍增加了。rime主打整句输入，若用形码打整句，每容错一个键就要扩大两三倍的检索范围，指数增长！？而其它形码输入法只要打满四五码就上屏了，相对轻松。佛振不做万能键是不是有这方面的顾虑？也许要优化检索方法或词典结构？容错、九宫格、万能键……看起来挺好的功能，但在rime这样一个综合的输入法平台上，只怕是impossible mission。

原贴在这里
http://tieba.baidu.com/mo/q----,sz@320_240-1-3---2/flr?pid=82508793361&kz=3917536050&pn=270&pinf=1_2_0

**Comment by osfans** [comment]
@xiaoqun2016  看來是這樣，以前我用數據庫格式保存碼表，萬能碼檢索時也會慢。

**Comment by frank-king** [comment]
@xiaoqun2016 形碼爲何要整句輸入？逐詞逐詞地輸入不是很好麼？每五碼自動上屏，不然打到後面出現重碼就很麻熕。（我平時都用倉頡快打模式，習慣打完一詞之後自動上屏）
輕鬆倉頡我之前未出現過卡頓的情況，至於您說的「每次擊鍵都偏離中心」，那是非常極端的情況，如果手殘到種地步，那還是用手寫爲妙。

**Comment by frank-king** [comment]
@xiaoqun2016 而且輕鬆倉頡輸入法也是限制了檢索數量的吧，每次並不會將所有可能的編碼都檢索出來。

**Comment by zcunlin** [comment]
@whjpji 喜欢整句就打整句，喜欢打单字就打单字，干嘛要强迫所有用形码的人都用定码长的打法啊。真烦人。

**Comment by frank-king** [comment]
@zcunlin 這不是重點好吧，我又未說所有用形碼的人都要用定碼長的啊？
我的意思是希望也能有容錯的功能，有時候按快了，編碼一錯就差起老遠。

**Comment by zcunlin** [comment]
@whjpji 整句输入与逐词输入不矛盾，不妨试试咯ㄟ( ▔, ▔ )ㄏ

**Comment by frank-king** [comment]
@osfans 還有就是我加入新版蒼頡六代的詞典進去怎麼就閃退了？

**Comment by osfans** [comment]
重新部署看看。我這裏沒有問題。

**Comment by osfans** [comment]
按錯了之後，目前可以點擊編碼區修正。

**Comment by frank-king** [comment]
可是部署了好幾次了啊，是不是我的trime改的有問題？

**Comment by frank-king** [comment]
@osfans 另外能讓長按延遲時間變短一點麼？

**Comment by frank-king** [comment]
@osfans 這是我自己設定的鍵盤

``` yaml
  cangjie6:
    ascii_mode: 0
    author: "1,729.000"
    height: 55
    keys: [{click: 1, long_click: "!"}, {click: 2, long_click: "@"}, {click: 3, long_click: "#"}, {click: 4, long_click: "$"}, {click: 5, long_click: "%"}, {click: 6, long_click: "^"}, {click: 7, long_click: "&"}, {click: 8, long_click: "*"}, {click: 9, long_click: "("}, {click: 0, long_click: ")"}, {click: q, label: "手", long_click: _}, {click: w, label: "田", long_click: "-"}, {click: e, label: "水", long_click: "+"}, {click: r, label: "口", long_click: "="}, {click: t, label: "廿", long_click: "|"}, {click: y, label: "卜", long_click: "\\"}, {click: u, label: "山", long_click: "["}, {click: i, label: "戈", long_click: "]"}, {click: o, label: "人", long_click: "{"}, {click: p, label: "心", long_click: "}"}, {width: 5}, {click: a, label: "日", long_click: select_all}, {click: s, label: "尸", long_click: Home}, {click: d, label: "木", long_click: End}, {click: f, label: "火", long_click: Page_Up}, {click: g, label: "土", long_click: Page_Down}, {click: h, label: "的", long_click: Left}, {click: j, label: "十", long_click: Down}, {click: k, label: "大", long_click: Up}, {click: l, label: "中", long_click: Right}, {click: Shift_L, width: 15}, {click: z, label: "片", long_click: "`"}, {click: x, label: "止", long_click: cut}, {click: c, label: "金", long_click: copy}, {click: v, label: "女", long_click: paste}, {click: b, label: "月", long_click: "~"}, {click: n, label: "弓", long_click: Insert}, {click: m, label: "一", long_click: Delete}, {click: BackSpace, width: 15}, {click: Hide, long_click: Color_switch}, {click: Keyboard_symbols, long_click: Keyboard_number}, {click: Mode_switch, long_click: Menu}, {click: space, width: 25}, {click: ",", long_click: "<", paging: Page_Up}, {click: ., has_menu: Page_Down, long_click: ">"}, {click: "?", long_click: "/"}, {click: Return, long_click: CommitComment, width: 15}]
    name: "倉頡六代鍵盤（40鍵）"
    width: 10
```

**Comment by osfans** [comment]
注意縮進和單引號、雙引號、\
單引號："'"
雙引號：'"'
\：'\'
你的是斜槓出了問題。
好像還有其他問題，我再改改。

``` yaml
  cangjie6:
    ascii_mode: 0
    author: "1,729.000"
    height: 55
    keys: [{click: 1, long_click: "!"}, {click: 2, long_click: "@"}, {click: 3, long_click: "#"}, {click: 4, long_click: "$"}, {click: 5, long_click: "%"}, {click: 6, long_click: "^"}, {click: 7, long_click: "&"}, {click: 8, long_click: "*"}, {click: 9, long_click: "("}, {click: 0, long_click: ")"}, {click: q, label: "手", long_click: _}, {click: w, label: "田", long_click: "-"}, {click: e, label: "水", long_click: "+"}, {click: r, label: "口", long_click: "="}, {click: t, label: "廿", long_click: "|"}, {click: y, label: "卜", long_click: '\'}, {click: u, label: "山", long_click: "["}, {click: i, label: "戈", long_click: "]"}, {click: o, label: "人", long_click: "{"}, {click: p, label: "心", long_click: "}"}, {width: 5}, {click: a, label: "日", long_click: select_all}, {click: s, label: "尸", long_click: Home}, {click: d, label: "木", long_click: End}, {click: f, label: "火", long_click: Page_Up}, {click: g, label: "土", long_click: Page_Down}, {click: h, label: "的", long_click: Left}, {click: j, label: "十", long_click: Down}, {click: k, label: "大", long_click: Up}, {click: l, label: "中", long_click: Right}, {click: Shift_L, width: 15}, {click: z, label: "片", long_click: "`"}, {click: x, label: "止", long_click: cut}, {click: c, label: "金", long_click: copy}, {click: v, label: "女", long_click: paste}, {click: b, label: "月", long_click: "~"}, {click: n, label: "弓", long_click: Insert}, {click: m, label: "一", long_click: Delete}, {click: BackSpace, width: 15}, {click: Hide, long_click: Color_switch}, {click: Keyboard_symbols, long_click: Keyboard_number}, {click: Mode_switch, long_click: Menu}, {click: space, width: 25}, {click: ",", long_click: "<", paging: Page_Up}, {click: ., has_menu: Page_Down, long_click: ">"}, {click: "?", long_click: "/"}, {click: Return, long_click: CommitComment, width: 15}]
    name: "倉頡六代鍵盤（40鍵）"
    width: 10
```

**Comment by osfans** [comment]
確實是斜槓的問題，你用的是哪裏下的cangjie6碼表？我來測試下。

**Comment by osfans** [comment]
長按時間修改style/longpress_timeout

``` yaml
style:
  longpress_timeout: 400 #按鍵超過800毫秒即為長按
```

**Comment by frank-king** [comment]
@osfans https://github.com/rime-aca/schemata/tree/master/Cangjie6

**Comment by frank-king** [comment]
@osfans 另外trime.yaml中的這句是甚麼意思啊？

``` yaml
  scj6:
    import_preset: cangjie5
```

**Comment by osfans** [comment]
已經修正：https://github.com/osfans/trime/releases/download/v3.0-beta2/trime-20160120.apk

那句話就是說，快速倉頡(scj6)默認用cangjie5的鍵盤。

**Comment by frank-king** [comment]
@osfans 蒼頡6的快打模式的狀態欄好像不對呢？只有「通用/增廣」「漢字/汉字」「半角/全角」三欄，「中文/西文」「，。/ , .」怎麼不見了？

**Comment by osfans** [comment]
switches裏面就是沒有啊。剛纔解決的問題就是：ascii_mode沒有指定states，把程序搞掛掉了。

https://github.com/rime-aca/schemata/blob/master/Cangjie6/cangjie6.schema.yaml#L18

你可以自己加switches。

**Comment by frank-king** [comment]
@osfans 另外我想問下把這個蒼頡六默認的字根「竹」改爲「的」要怎麼改呢？我改了cangjie6.schema.yaml文件但是沒用？

``` yaml
translator:
  dictionary: cangjie6
  prism: cangjie6_express
  enable_user_dict: true
# 不想自動調頻的話，將上條中「true」改爲「false」
  user_dict: cangjie6_express
  enable_charset_filter: true
  enable_sentence: false
  sentence_over_completion: true
  preedit_format:
    - xlit|abcdefghijklmnopqrstuvwxyz|日月金木水火土的戈十大中一弓人心手口尸廿山女田止卜片|
  comment_format:
    - xlit|abcdefghijklmnopqrstuvwxyz~|日月金木水火土的戈十大中一弓人心手口尸廿山女田止卜片・|
```
