### ISSUE TITLE
在trime上配置了Ctrl Esc键，但是在termux中没有效果。trime如何和Termux一起使用，实现修饰键Ctrl同样的效果？

### ISSUE THREAD

**Issue by iT-Boyer** [osfans/trime#444]
trime.custom.yaml
```yaml
 "preset_keys/emacs_commit":
    label: 完成
    text: "{Control+c}{Control+c}"


# 用data_time替换原预设26键键盘中的time
  "preset_keyboards/qwerty/keys/@26/long_click": emacs_commit
```
