### ISSUE TITLE
如何在trime状态上新增修饰键 Control、Esc等？

### ISSUE THREAD

**Issue by iT-Boyer** [osfans/trime#497]
默认的trime状态栏显示如下几项状态切换键：
```yaml
# rime狀態
  Mode_switch: {toggle: ascii_mode, send: Mode_switch, states: [ 中文, 西文 ]}
  Zenkaku_Hankaku: {toggle: full_shape, send: Mode_switch, states: [ 半角, 全角 ]}
  Henkan: {toggle: simplification, send: Mode_switch, states: [ 漢字, 汉字 ]}
  Charset_switch: {toggle: extended_charset, send: Mode_switch, states: [ 常用, 增廣 ]}
  Punct_switch: {toggle: ascii_punct, send: Mode_switch, states: [ 。，, ．， ]}

```
是否支持定制，在后面新增修饰键，例如`Tab、Control、Esc` 。
1. 该如何新增键位？
2. 是否可以实现组合键，选中后，和其他键位组合，例如和`g`组合`Control+g`等？

目前使用键位绑定实现组合键功能
如下：在`/sdcard/rime/trime.custom.yaml`中绑定键位
1. 声明组合键
```yaml
  "preset_keys/cg":
       label: 撤销
       send: Control+g
```
2. 绑定键位
```yaml
"preset_keyboards/qwerty0/keys/@33/long_click": cg
```

**Comment by walk143** [comment]
一种思路：把状态栏关闭，布局里面的第一排放这些键。

**Comment by iT-Boyer** [comment]
> 一种思路：把状态栏关闭，布局里面的第一排放这些键。

没找到trime状态栏的配置项，这个思路很好，是要同源码才能实现吗？

**Comment by walk143** [comment]
就是在按键布局里，比如
```yaml
    - {click: Zenkaku_Hankaku, long_click: Henkan, width: 15}
```
可选按键在`trime.yaml`中，示例如下
```yaml
  Mode_switch: {toggle: ascii_mode, send: Mode_switch, states: [ 中文, 西文 ]}
  Zenkaku_Hankaku: {toggle: full_shape, send: Mode_switch, states: [ 半角, 全角 ]}
  Henkan: {toggle: simplification, send: Mode_switch, states: [ 漢字, 汉字 ]}
  Charset_switch: {toggle: extended_charset, send: Mode_switch, states: [ 常用, 增廣 ]}
  Punct_switch: {toggle: ascii_punct, send: Mode_switch, states: [ 。，, ．， ]}
```
