### ISSUE TITLE
候选框悬浮窗模式下，候选窗口无法跟随光标焦点

### ISSUE THREAD

**Issue by yanhuacuo** [osfans/trime#561]
以下所有反馈，全部基于早期（今年2月份）版本表现正常，而当前版本表现异常。

基于当前版本的 [trime.yaml](https://github.com/osfans/trime/blob/develop/app/src/main/assets/rime/trime.yaml) ，作局部改造，以期获取正常的「候选框悬浮窗」，这个对于安卓平板外接键盘打字非常重要。

改造后的文件：[新的 trime.yaml ](https://github.com/yanhuacuo/b-sty/blob/master/trime.yaml)

涉及到的代码：

``````
style:
  auto_caps: false #自動句首大寫:true|false|ascii
  background_dim_amount: 0.5
  candidate_font: 98WB-1.otf #候選字型
  candidate_padding: 5 #候選項內邊距
  candidate_spacing: 0.5 #候選間距
  candidate_text_size: 22 #候選字號
  candidate_use_cursor: true #高亮候選項
  candidate_view_height: 28 #候選區高度
  color_scheme: default #配色方案
  comment_font: 98WB-1.otf #編碼提示字型
  comment_height: 12 #編碼提示區高度
  comment_on_top: true #編碼提示在上方或右側
  comment_text_size: 12 #編碼提示字號
  hanb_font: 98WB-1.otf #擴充字型
  horizontal: true #水平模式
  horizontal_gap: 1 #鍵水平間距
  keyboard_padding: 0 #竖屏模式下，屏幕左右两侧与键盘的距离（曲面屏减少误触）
  keyboard_padding_left: 0 #竖屏屏模式下，左手键盘布局，屏幕左侧与键盘的距离
  keyboard_padding_right: 40 #竖屏屏模式下，左手键盘布局，屏幕右侧与键盘的距离
  keyboard_padding_bottom: 0 #竖屏模式下，屏幕下边缘与键盘的距离（避免误触发全面屏手势）
  keyboard_padding_land: 40 #横屏模式下，屏幕左右两侧与键盘的距离（避免横屏按键过度拉伸变形）
  keyboard_padding_land_bottom: 0 #横屏模式下，屏幕下侧与键盘的距离
  layout: #懸浮窗口設置
    position: right #位置：left|right|left_up|right_up|fixed|bottom_left|bottom_right|top_left|top_right(left、right需要>=Android5.0)
    min_length: 1 #最小詞長
    max_length: 10 #超過字數則換行
    sticky_lines: 1 #固頂行數
    max_entries: 9 #最大詞條數
    min_check: 1 #只要前n个候选词有长度大于等于min_length的词，就会把长度符合以及之前的词全部加到悬浮窗内。
    all_phrases: true #所有滿足條件的詞語都顯示在窗口
    border: 2 #邊框寬度
    max_width: 1000 #最大寬度，超過則自動換行
    max_height: 800 #最大高度
    min_width: 40 #最小寬度
    min_height: 0 #最小高度
    margin_x: 5 #水平邊距
    margin_y: 5 #豎直邊距
    margin_bottom: 0 #底部边距 （用于适配特定背景图）
    real_margin: 3 #屏幕左右边缘和悬浮窗之间的距离
    line_spacing: 0 #候选詞的行間距(px)
    line_spacing_multiplier: 1.0 #候选詞的行間距(倍數)
    spacing: 1 #與預編輯或邊緣的距離
    round_corner: 12 #窗口圓角
    alpha: 0xdd #透明度(0-255)
    elevation: 5 #陰影(>=Android5.0)
    movable: once #是否可移動窗口，或僅移動一次 true|false|once
  window: #悬浮窗口組件
    - {start: "", composition: "%s", end: "", letter_spacing: 0, end: " "} #letter_spacing需要Android5.0。TODO: 不为0时，会导致不换行的问题
    - {start: "\n", label: "%s.", candidate: "%s", comment: " %s", end: " ", sep: "\n"}  #label: "%s.", 序号;start: "\n", 换行
  key_font: symbol.ttf #鍵盤字型
  key_height: 44 #鍵高
  key_long_text_size: 14 #長標籤字號
  key_text_size: 22 #鍵字號
  key_width: 10.0 #鍵寬，佔螢幕寬的百分比
  keyboards: [.default, letter, number, symbols] #鍵盤配置：自動鍵盤、字母、數字、符號
  label_text_size: 22 #標籤字號
  label_font: label.ttf #編標籤字型
  latin_font: latin.ttf #西文字型
  latin_locale: en_US #西文語言
  locale: zh_TW #預設語言 zh_TW,zh_CN,zh_HK,""
  preview_font: latin.ttf #按鍵提示字型
  preview_height: 60 #按鍵提示高度
  preview_offset: -12 #按鍵提示縱向偏移
  preview_text_size: 40 #按鍵提示字號
  proximity_correction: true #按鍵糾錯
  reset_ascii_mode: false #顯示鍵盤時重置爲中文狀態
  round_corner: 8 #按鍵圓角半徑
  shadow_radius: 0.0 #按鍵陰影半徑
  speech_opencc_config: s2t.json #語音輸入簡繁轉換
  symbol_font: symbol.ttf #符號字型
  symbol_text_size: 10 #符號字號
  text_font: 98WB-1.otf #編碼字型
  #text_height: 22 #編碼區高度
  text_size: 16 #編碼區字號
  vertical_correction: 0
  vertical_gap: 1 #鍵盤行距
  long_text_font: comment.ttf #剪贴板等可能包含大段文本使用的字体
  #background_folder: #背景图保存在background目录下的哪个子目录
  key_long_text_border: 1
``````

![PIC](https://raw.githubusercontent.com/yanhuacuo/b-sty/master/trime-bug.jpg)
