### ISSUE TITLE
全局配置round_corner和key_text_size失效的问题在3.2.3中依然存在

### ISSUE THREAD

**Issue by SivanLaai** [osfans/trime#564]
**Describe the bug**
全局配置round_corner和key_text_size失效的问题在3.2.3中依然存在

**To Reproduce**
Steps to reproduce the bug:
1. 呼唤出输入法
2. 主界面通过全局配置文件配置的键盘全部在文本尺寸和圆角上失效

**Expected behavior**
显示配置中的尺寸大小和圆角弧度

**Log**
If applicable, add crash log to quick focus your problem.

**Screenshots**
### 圆角在全局配置中无法生效
全局配置：
```yaml
style:
  ...
  round_corner: *NJY #按键圆角半径，不生效，实际值是12，显示的是默认的5
```
效果如下，全部圆角是默认的5：

![a98d5ce2c0c72ad548596ec35d7ba26](https://user-images.githubusercontent.com/33414148/138995249-7b12b48e-0aa3-43cf-89b9-d8b06ff64e0e.jpg)
### 键盘尺寸大小问题
```yaml
style:
  ...
  key_text_size: 21 #键字号，不生效，这个在局部key上设置key_text_size解决
```
作如下修改生效：
```yaml
preset_keyboards:
  default:
    ...
    - {click: BackSpace, swipe_left: Clear, swipe_up: Candidate_switch1, key_text_offset_y: 0, key_back_color: bksb, hilited_key_back_color: bksh, key_symbol_color: bkss, key_text_color: bkst, width: 13, key_text_size: 21}

```

**Smartphone (please complete the following information):**
 - Device: [Mate 30 pro]
 - OS: [Harmony OS 2]
 - Version: [3.2.3]
 - Theme: [同文风增强.trime.yaml](https://github.com/SivanLaai/rime-pure/blob/master/trime/rime/%E5%90%8C%E6%96%87%E9%A3%8E%E5%A2%9E%E5%BC%BA%E7%89%88.trime.yaml)

**Additional context**
### 应该是在这里读取了默认的配置，全局没有生效
``` Key.java:145
    key_text_size = YamlUtils.INSTANCE.getPixel(mk, "key_text_size", 22);
    symbol_text_size = YamlUtils.INSTANCE.getPixel(mk, "symbol_text_size", 10);
    key_text_color = Config.getColor(context, mk, "key_text_color");
    hilited_key_text_color = Config.getColor(context, mk, "hilited_key_text_color");
    key_back_color = config.getDrawable(mk, "key_back_color");
    hilited_key_back_color = config.getDrawable(mk, "hilited_key_back_color");
    key_symbol_color = Config.getColor(context, mk, "key_symbol_color");
    hilited_key_symbol_color = Config.getColor(context, mk, "hilited_key_symbol_color");
    round_corner = YamlUtils.INSTANCE.getFloat(mk, "round_corner", 5); 

```
