### ISSUE TITLE
【v3.2.4】`上檔鍵` 激活狀態下部分編輯鍵不生效

### ISSUE THREAD

**Issue by rainhear** [osfans/trime#622]
## 漏洞描述

`3.2.4` 版本中，`上檔鍵` 激活狀態下 `全選` `剪切` `複製` `撤銷` `重做` 編輯鍵不生效

## 重現漏洞

重現漏洞的步驟：

1. 更新至 #619 後的編譯版，文本編譯區域調出 `編輯鍵盤`
2. 當 `上檔鍵 Shift` 處於激活狀態，`全選 select_all` `剪切 cut` `複製 copy` `撤銷 undo` `重做 redo` 編輯鍵不生效
3. 當 `上檔鍵` 處於關閉狀態，則上述編輯鍵正常生效

## 預期行為

無論 `上檔鍵` 是否處於激活狀態，`全選` `剪切` `複製` `撤銷` `重做` 編輯鍵等均應當生效

## 日誌

``` yaml
# 安卓按鍵配置
android_keys:
  property:
    shift_lock: Shift鎖定 # ascii_long: 英文長按中文單按鎖定, long: 長按鎖定, click: 單按鎖定

# 預設按鍵
preset_keys:
  Shift_L: {label: '⇪', preview: '⇪', functional: true, shift_lock: long, send: Shift_L} # 用於主鍵盤
  Shift_L1: {label: '☩', preview: '☩', functional: true, shift_lock: click, send: Shift_L} # 用於編輯鍵盤
  space: {preview: '⎵', repeatable: false, functional: true, send: space} # 用於主鍵盤
  space1: {label: '⎵', preview: '⎵', repeatable: true, functional: true, send: space} # 用於編輯鍵盤
  Return: {label: '⏎', preview: '⏎', repeatable: false, functional: true, send: Return}
  Tab: {label: '↹', preview: '↹', repeatable: false, functional: true, commit: '	'}
  BackSpace: {label: '⌫', preview: '⌫', repeatable: true, functional: true, send: BackSpace}
  Delete: {label: '⌦', preview: '⌦', repeatable: true, functional: true, send: Delete}

  Up: {label: '▲', preview: '▲', repeatable: true, functional: false, send: Up}
  Down: {label: '▼', preview: '▼', repeatable: true, functional: false, send: Down}
  Left: {label: '◀', preview: '◀', repeatable: true, functional: false, send: Left}
  Right: {label: '▶', preview: '▶', repeatable: true, functional: false, send: Right}
  Home: {label: '⩞', preview: '⩞', functional: false, send: Home}
  End: {label: '⩣', preview: '⩣', functional: false, send: End}
  Page_Up: {label: '⩓', preview: '⩓', repeatable: true, functional: false, send: Page_Up}
  Page_Down: {label: '⩔', preview: '⩔', repeatable: true, functional: false, send: Page_Down}

  select_all: {label: '☑', preview: '☑', functional: true, send: Control+a}
  cut: {label: '✄', preview: '✄', functional: true, send: Control+x}
  copy: {label: '❐', preview: '❐', functional: true, send: Control+c}
  paste: {label: '✎', preview: '✎', functional: true, send: Control+v}
  redo: {label: '↻', preview: '↻', repeatable: false, functional: true, send: Control+y} # >= Android 6.0
  undo: {label: '↺', preview: '↺', repeatable: false, functional: true, send: Control+z} # >= Android 6.0

  Keyboard_default: {label: '⌨', functional: true, send: Eisu_toggle, select: .default}
  Keyboard_number: {label: '123', functional: true, send: Eisu_toggle, select: number}
  Keyboard_symbols: {label: '❉', functional: true, send: Eisu_toggle, select: symbols}
  Keyboard_edit: {label: '‹ɪ›', functional: true, send: Eisu_toggle, select: edit}
  Clipboard: {label: '📋', send: function, command: liquid_keyboard, option: "clipboard"}

# 鍵盤佈局
preset_keyboards:
  # 編輯鍵盤
  edit:
    author: 聽雨客
    name: 編輯
    width: 16.6
    height: 40
    ascii_mode: 0
    keys:
      # 第一行
      - {click: Clipboard}
      - {click: redo}
      - {click: Page_Up}
      - {click: Up}
      - {click: Home}
      - {click: space1}

      # 第二行
      - {click: Tab}
      - {click: undo}
      - {click: Left}
      - {click: Shift_L1}
      - {click: Right}
      - {click: Return}

      # 第三行
      - {click: Keyboard_symbols}
      - {click: Delete}
      - {click: Page_Down}
      - {click: Down}
      - {click: End}
      - {click: BackSpace}

      # 第四行
      - {click: Keyboard_number}
      - {click: select_all}
      - {click: cut}
      - {click: copy}
      - {click: paste}
      - {click: Keyboard_default}
```

## 截圖

![上檔鍵狀態](https://user-images.githubusercontent.com/60956322/145079505-4263219a-2390-47c5-9c20-e6432bb98a1c.png)

## 智能手機（請填寫以下信息）

- 設備：【ZUK Z2 Pro】
- 操作系統：【Android 7.0】
- 版本：【3.2.4】
- 主題：【個人主題】

## 附加內容

- 與 @walk143 討論時，`walk143` 認為應當類同桌面端組合鍵邏輯，上檔鍵激活狀態下此類按鍵可視為新組合，未必需要生效
- 敝人觀點，在調出 `編輯鍵盤` 編輯文本時：
  - 開始點擊激活 `上檔鍵`，再使用方向鍵等選中文本
  - 接著點擊關閉 `上檔鍵`，最後點擊 `剪切` `複製` `撤銷` `重做` 等鍵執行操作
- 如此反覆點擊 `上檔鍵` 的行為，無疑加重了擊鍵負擔
- 且用戶若忽視了 `上檔鍵` 處於激活狀態，文本將無法正常記錄並被剪貼板獲取
