### ISSUE TITLE
状态栏中的开关符号排列异常

### ISSUE THREAD

**Issue by yanhuacuo** [osfans/trime#631]
用的 [最新时间节点](https://github.com/osfans/trime/commit/215e8b6b4480e788902ab972c0cab49c409c3a1f)  的包：

在方案补丁下，写了「布局切换开关」：

```yml
patch:
  switches:
  - name: ascii_mode
    states: [ 中,英 ]
    reset: 1
  - name: zh_trad
    reset: 0
    states: [ 简,繁 ]
  - name: 98wb_spelling_rk
    reset: 1
  - name: 98wb_spelling
    reset: 1    
    states: [ 隐,显 ]    
  - name: jiayin
    reset: 1
  - name: gb2312
    reset: 0
    states: [ 扩,常 ]
  - options: [ _keyboard_.default, _keyboard_zhuji-0, _keyboard_98wb]
    states: [ 标,助,⌨ ]
```

「标」、「助」、「⌨」，可以在三种不同布局下循环切换，在旧版中，开关符靠底部，比较和谐整齐。

新版中，也不能说一定是有问题，但是它在『居中』时，是真的挺违和的。如下图：

![pic](https://raw.githubusercontent.com/yanhuacuo/wiz/main/1.jpg)

![pic](https://raw.githubusercontent.com/yanhuacuo/wiz/main/2.jpg)

![pic](https://raw.githubusercontent.com/yanhuacuo/wiz/main/3.jpg)

![pic](https://raw.githubusercontent.com/yanhuacuo/wiz/main/4.jpg)
