### ISSUE TITLE
设计：区分键盘按键的状态

### ISSUE THREAD

**Issue by iovxw** [osfans/trime#674]
**Is your feature request related to a problem? Please describe.**

目前 trime 键盘上的按键，对于用户的操作，有下面这些配置项

```yml
  when:
    ascii: 西文標籤
    paging: 翻頁標籤
    has_menu: 選單標籤
    composing: 輸入狀態標籤
    #always: 始終
    #hover: 滑過
    combo: 並擊
    click: 單按
    long_click: 長按
    #double_click: 雙按
    swipe_left: 左滑
    swipe_right: 右滑
    swipe_up: 上滑
    swipe_down: 下滑
```

除去现在没实现的几个，这些配置项实际可以分成两类

`click` `combo` `long_click` `swipe_*` 都很好理解，就是配置在用户进行相应动作时要触发的 `preset_keys` 中的键

但 `ascii` `paging` `has_menu` `composing` 这几个，是配置的键盘在不同状态下，把 `click` 替换掉的建

所以它们本质是 `ascii_click` `paging_click` ...

如果用户想单独配置在翻页时或者英文状态下某个按键的上滑操作，是做不到的

**Describe the solution you'd like**

将按键的状态与操作拆开

在不同的状态下，`click` `combo` `long_click` `swipe_*` 触发不同的键

比如在英文模式中 Shift 按下是大写单个字母，上滑是大写锁定，但在中文输入过程中，Shift 按下是分词，上划无作用

这个功能可以在保留兼容性的前提下实现

比如现在 tongwenfeng 里的一个配置是

```yml
- {click: Shift_L, composing: delimiter}
```

其中 `Shift_L` 和 `delimiter` 都是在 `preset_keys` 中定义的键

需要做的修改，就是允许 `composing` 不止接受 `preset_keys` 中定义的键，还接受一个完整的 `preset_keyboards` 里 `keys` 里这样的包括动作的键

就是允许套娃

修改后上面的配置的等价写法是这样的（当然保留旧的写法）：

```yml
- {click: Shift_L, composing: {click: delimiter}}
```

扩展一下大概这种样子：

```yml
- {click: Shift_L, ascii: {click: ..., swipe_up: ...}, composing: {click: delimiter, swip_up: ..., long_click: ...}}
```

**Describe alternatives you've considered**

另一种保留兼容性的写法是新加一个 when 字段，接受一个数组

```yml
- {click: Shift_L, when: [{state: ascii, click: ..., swipe_up: ...}, {state: composing, click: ..., swipe_up: ...}]}
```

**Additional context**

可以新加几个状态，比如 shifted, alted, 来解决 #578 中的问题
