### ISSUE TITLE
功能：自定義按鍵音

### ISSUE THREAD

**Issue by DaengGWokFook** [osfans/trime#71]
上述三樣功能其它輸入法幾乎都有，要加上去應該不難。最好能自定義。

**Comment by Prcuvu** [comment]
按键震动已经实现，可以自定义时长。

**Comment by DaengGWokFook** [comment]
如何設置按鍵震動？

**Comment by osfans** [comment]
背景现在只能颜色 还不能是图片 声音只能是系统声音

**Comment by xiaoqun2016** [comment]
打补丁： 

``` yaml
#trime.custom.yaml 
patch:
  "style/key_vibrate_duration": 9 #震动强度
  "style/key_vibrate": true #震动开关
  "style/key_sound": true #声音开关
```

更多参数可参考trime.yaml详解
