### ISSUE TITLE
switches的reset参数似乎没有生效

### ISSUE THREAD

**Issue by jacobax** [osfans/trime#723]
**Describe the bug**
切换编辑框, 中英状态不会恢复到reset所设定的状态, 3.2.5无此问题

```
switches:
  - name: ascii_mode
    reset: 0
    states: [ 中, 英 ]
```

**Smartphone (please complete the following information):**
 - Device: redmi
 - OS: miui 13
 - Version: 3.2.6
 - Theme: Tongwenfeng
