### ISSUE TITLE
求教合理的调试流程，及部署和回厂默认的具体含义

### ISSUE THREAD

**Issue by boboIqiqi** [osfans/trime#73]
大家平时都是怎么调试一个输入方案，或者键盘布局的。
我先说我的，大家看看是哪里出问题了。
我现在用gVim编辑（刚学的，用得不熟，后面还要向大家学习）
## 1.编辑文件

主要编辑： `trime.custom.yaml` 和 `wubi86_double_key.schema.yaml`
## 2. 拷贝到手机

用下面的脚本push到 /sdcard/rime下面

``` bash
:: update.bat
adb push trime.custom.yaml /sdcard/rime
adb push wubi86_double_key.schema.yaml /sdcard/rime
pause
```
## 3.部署

就是点击同文桌面图标，进入配界面，点击部署

然后，某次我发现它的错误好像会累积。比如，下面是我pull出来的一个trime.yaml文件

``` yaml
  qwert:    #这个其实是我某次拼写错了，然后就一直在这里了
    ascii_mode: 1
  qwerty:
    ascii_mode: 1
    author: "osfans <waxaca@163.com>"
    height: 55
    keys: [{click: q, long_click: "!", swipe_up: 1}, {click: w, long_click: "@", swipe_up: 2}, {click: e, long_click: "#", swipe_up: 3}, {click: r, long_click: "$", swipe_up: 4}, {click: t, long_click: "%", swipe_up: 5}, {click: y, long_click: "^", swipe_up: 6}, {click: u, long_click: "&", swipe_up: 7}, {click: i, long_click: "*", swipe_up: 8}, {click: o, long_click: "(", swipe_up: 9}, {click: p, long_click: ")", swipe_up: 0}, {width: 5}, {click: a, long_click: select_all, swipe_down: Down, swipe_left: Left, swipe_right: Right, swipe_up: Up}, {click: s, long_click: "~", swipe_down: Page_Down, swipe_left: Home, swipe_right: End, swipe_up: Page_Up}, {click: d, long_click: "-", swipe_down: _}, {click: f, long_click: "+", swipe_down: "="}, {click: g, long_click: "\\", swipe_down: "|"}, {click: h, long_click: "[]", swipe_left: "[", swipe_right: "]"}, {click: j, long_click: "{}", swipe_left: "{", swipe_right: "}"}, {click: k, long_click: ":"}, {click: l, long_click: ";"}, {width: 5}, {click: Shift_L, composing: "'", send_bindings: true, width: 15}, {click: z, long_click: "`"}, {click: x, long_click: cut}, {click: c, long_click: copy}, {click: v, long_click: paste}, {click: b, long_click: Time, swipe_up: Date}, {click: n, long_click: "\""}, {click: m, long_click: "'"}, {click: BackSpace, width: 15}, {click: Mode_switch, long_click: Menu, width: 15}, {click: Keyboard_symbols, long_click: Keyboard_number}, {click: ",", long_click: "<", paging: Page_Up}, {click: space, width: 30}, {click: ., has_menu: Page_Down, long_click: ">"}, {click: "/", long_click: "?"}, {click: Return, long_click: CommitComment, width: 15}]
    name: "預設26鍵"
    width: 10
  qwerty0:
```

`qwert:    #这个其实是我某次拼写错了，然后就一直在这里了`
## 4.回厂

我点击了一下配置界面中 的"回厂"，选中了trime.yaml文件，确定。
## 5.重新布署出错

我又重新push我写的配置文件到/sdcard/rime/，然后进行部署。

这回，好像找不到qwerty键盘了。原来一直正常可以工作的配置文件，现在部署以后，点击切换到
Keybroad_qwerty的按键后，只是输出一个Keyborad_qwerty字符串。但是trime.yaml文件中又有qwerty键盘

我帖上我pull出来的trime.yaml文件。我的文件，上一个帖子中已经贴了。
有点困了，实在不知道为什么。所以先把它帖出来，如果是个弱智白痴问题，大家不要骂我。

这个问题，我前两天调试的也碰到过两次，我把rime文件夹全清了以后，重新push /brise/supplement文件夹下的所有文件,以后那三个必需文件，然后就好了。不过我还是想知道为什么。
