### ISSUE TITLE
多方案套用單個鍵盤

### ISSUE THREAD

**Issue by DaengGWokFook** [osfans/trime#80]
例如：倉頡5和倉頡快打用同樣鍵盤
key board：倉頡
schema：{cangjie5, cangjie5express}

**Comment by osfans** [comment]
可以這樣：

``` yaml
#trime.yaml
preset_keyboards:
  cangjie5express:
    import_preset: cangjie5
```

或者這樣：

``` yaml
#cangjie5express.schema.yaml
style:
  keyboards:
    - cangjie5
    - symbols
    - number
```

再或者schema名字改成`cangjie5_express`可能能自動找到。
