### ISSUE TITLE
中西文输入状态在切换过数字小键盘或符号键盘后无法保留

### ISSUE THREAD

**Issue by Kruegerrr** [osfans/trime#808]
**Describe the bug**
中西文输入状态在切换过数字小键盘或符号键盘后无法保留

**To Reproduce**
Steps to reproduce the bug:
1. 切换到西文输入
2. 切换到数字小键盘或符号键盘
3. 切换回一般输入键盘
4. 发现最初的西文输入状态已变成中文

**Expected behavior**
在输入过程中切换到数字小键盘或符号键盘不应影响到中西文输入状态，因此如果在切换前是西文输入状态，切换后仍应保持西文输入状态。

**Screenshots**

https://user-images.githubusercontent.com/109552167/180436786-e4c38b70-b897-49ec-8266-32968f3c6b3b.mp4

**Smartphone (please complete the following information):**
 - OS: Android 11
 - Theme: Tongwenfeng
 - Version: 3.2.7
 - Build info: 
   ```
    Build: null 
    Date: 2022-07-07 10:11 UTC 
    Commit: v3.2.6-90-g68de0c6, 2022-06-29 22:45:02 +0800 
    Branch:  
    Repository: https://github.com/osfans/trime
   ```
