### ISSUE TITLE
西文模式下無法用滑動來打大寫字母

### ISSUE THREAD

**Issue by syimyuzya** [osfans/trime#820]
**Describe the bug**

我的自定義軟鍵盤，字母鍵有類似這樣的配置：

```yaml
...
- {label: '手', click: 'q', hint: 'Q', swipe_up: 'Q', long_click: '_'}
- {label: '田', click: 'w', hint: 'W', swipe_up: 'W', long_click: '-'}
- {label: '水', click: 'e', hint: 'E', swipe_up: 'E', long_click: '+'}
- {label: '口', click: 'r', hint: 'R', swipe_up: 'R', long_click: '='}
...
- {click: ';', swipe_up: ':', long_click: ':'}
```

但是在 3.2.7 版的西文模式下，swipe_up 的項只對符號和數字有效（比如「;」鍵向上滑是「:」或者預設鍵盤頂排鍵可以上滑打數字等，而利用↑的配置想上滑打大寫字母卻完全沒有反應）。

【而更奇怪的是，中文模式下卻能正常的用它（但這樣會先將大寫字母打進編輯欄中，再按 space 才能出字，很麻煩）

**To Reproduce**

1. 在 trime.custom.yaml 中為某輸入法配置如上所述的鍵盤
2. 重新部署
3. 輸入法切為西文模式
4. 試着用字母鍵上滑輸入大寫字母

**Expected behavior**

應當能打出大寫字母。

**Actual behavior**

完全沒有效果。

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mix 4
 - OS: Android 12
 - Theme: Default
 - Version: 3.2.7
 - Build info: 
   ```
   Build: null
   Date: 2022-07-07 10:11 UTC
   Commit: v3.2.6-90-g68de0c6, 2022-06-29 22:45:02 +0800
   Branch:
   Repository: https://github.com/osfans/trime
   ```
