### ISSUE TITLE
能不能声调替换（覆盖）？

### ISSUE THREAD

**Issue by fhxu** [osfans/trime#90]
我做了个双拼+声调筛选的方案
用的时候发现个个人问题，有时候声调输入的不对，需要删除错误的声调，才能输入正确的
我想能不能，如果前面输入的不对的话，后面直接输入，不用删除前面输入的，而是直接替换成后面的
如：我第一次输入的是1声，可是不对，又接着输入3，也不对，我不用删除直接接着输入4正确，这样子！

**Comment by osfans** [comment]
好像librime目前不支持修改輸入字串。

**Comment by fhxu** [comment]
感谢回复！
不支持，那太遗憾了！！希望以后能够支持~~

**Comment by osfans** [comment]
@xiaoqun2016 幫忙確認下。
@lotem 如果可以做的話，我就轉到librime了。

**Comment by xiaoqun2016** [comment]
想法挺好，但目前好像不支持。  
是否可以通过类似`xform/\d(\d)/$1/`这样的拼写运算来处理？

**Comment by zaqzrh** [comment]
怎么没想到呢！正需要这功能呀。

@osfans @lotem librime能实现吗？想想吧。

@xiaoqun2016 这拼写运算要作码表吗？试了好像不行呢。

**Comment by osfans** [comment]
其實同文2.0中，是有實現這個功能的。現在librime好像還沒有。

**Comment by fhxu** [comment]
@osfans 同文我也在用，请问我怎么操作才能应实现这个功能！谢谢！

**Comment by osfans** [comment]
3.0後臺用librime了，所以還沒有這個功能。

**Comment by fhxu** [comment]
@osfans 好的，那我就不瞎折腾了！后续版本如是有可能的话，还是希望能够得到支持！

**Comment by lotem** [comment]
可以黑支持有限次改寫，即通過拼寫運算展開 `ping1 -> ping21, ping31, ping41` 等等。

要想優雅地支持，還得改寫輸入串。

**Comment by lotem** [comment]
Pending on https://github.com/rime/librime/issues/85

**Comment by xiaoqun2016** [comment]
声调任意覆盖的一个技巧，供参考。

以地球拼音为例：  
[效果演示.mp4](https://github.com/xiaoqun2016/doc/raw/master/%E5%A3%B0%E8%B0%83%E8%A6%86%E7%9B%96.mp4)  （1.3M）  

补丁如下：  

```yaml
# terra_pinyin.custom.yaml
patch:
  "engine/processors":
    - ascii_composer
    - recognizer
    - speller
    - key_binder  #移到speller后面
    - punctuator
    - selector
    - navigator
    - express_editor
  "speller/finals": ';/,\'  #声调仅作末码
  "key_binder/bindings":
  #使重复的声调失效
    - {accept: semicolon, toggle: noop, when: composing}
    - {accept: slash, toggle: noop, when: composing}
    - {accept: comma, toggle: noop, when: composing}
    - {accept: backslash, toggle: noop, when: composing}
```

默认主题微调
```yaml
# trime.custom.yaml
patch:
  "preset_keyboards/terra_pinyin/keys/@19":
    click: ";"
    composing: T1
    long_click: ":"
  "preset_keyboards/terra_pinyin/keys/@27":
    click: "/"
    composing: T2
    long_click: "?"
  "preset_keyboards/terra_pinyin/keys/@28":
    click: ","
    composing: T3
    long_click: "<"
  "preset_keyboards/terra_pinyin/keys/@35":
    click: "\\"
    composing: T4
    long_click: .
  "preset_keys/T1":
    label: "ˉ"
    text: "{semicolon}{BackSpace}{semicolon}"  #奇技淫巧
  "preset_keys/T2":
    label: "ˊ"
    text: "{slash}{BackSpace}{slash}"
  "preset_keys/T3":
    label: "ˇ"
    text: "{comma}{BackSpace}{comma}"
  "preset_keys/T4":
    label: "ˋ"
    text: "{backslash}{BackSpace}{backslash}"
```

*改写输入串已经开了专题（ librime#85 ），此处暂告一段落。 *
