### ISSUE TITLE
reset_ascii_mode: true #显示键盘时重置为中文状态能否针对不同皮肤/输入法设置

### ISSUE THREAD

**Issue by TingTing1990** [osfans/trime#904]
目前这个字段好像是针对所有输入法/皮肤生效的，我主要用九宫输入法，目前这个字段设置为“true”来避免九宫输入法带来的西文键盘的问题，但是如果我切换到26键的中文键盘不想强制中文，请问这个字段的功能能否达成这个功能？
PS：如果现在有这个功能请告知如何设置，谢谢！

**Comment by WhiredPlanck** [comment]
在方案文件（`*.schema.yaml`）里有像这么一处：
```yaml
switches:
  - name: ascii_mode
    reset: 0
    states: [中文, 西文]
```
其中的 `reset: 0` 改为 `reset: 1`，如果没有则新增。试试看有没有效。
