### ISSUE TITLE
20160708版 trime.yaml 部署无效

### ISSUE THREAD

**Issue by X1aomu** [osfans/trime#96]
刚装上trime后的前几次部署都是有效的，可就在我某次再更改 trime.custom.yaml 文件后，部署结束没有效果，发现 trime.yaml 文件没有改动，将 trime.yaml 恢复原厂后再部署也是同样的问题，而后再改动 trime.custom.yaml 文件（只是在中间插入一空行，是为了让 custom 文件的时间更新），再部署问题依旧。部署会花十几秒钟，但过后 trime.yaml 还是部署前的样子。

目前我还没有试过完全重新部署一次，因为那用时太久了，我将在今天睡前试试看。

以下是我目前 trime.custom.yaml 文件的前面部分，整个文件很长，我想如果是我文件的中间出了问题，我想trime.yaml也不会一点变化都没有的，不知这么理解是否正确。

``` yaml
# trime.custom.yaml
# encoding: utf-8
# author: zl
patch:
  #"style/color_scheme": google

  "style/multitap_interval": 400
  "style/loogpress_timeout": 500
  "style/reset_ascii_mode": false

  #"style/candidate_text_size": 6 # 候選字大小
  #"style/comment_text_size": 3 # `編碼提示大小`
  #"style/candidate_view_height": 6 # 候選區高度
  #"style/comment_height": 6 # 編碼提示區高度
  "style/horizontal_gap": 2
  "style/vertical_gap": 1

  "preset_keyboards/zl_default":
    name: alphabet_num
    author: zl
    ascii_mode: 0
    width: 10
    height: 45
    keys:
      # 第一行
      #- {click: 1, long_click: "!"}
      #- {click: 2, long_click: "@"}
      #- {click: 3, long_click: "#"}
      #- {click: 4, long_click: "$"}
      #- {click: 5, long_click: "%"}
      #- {click: 6, long_click: "^"}
      #- {click: 7, long_click: "&"}
      #- {click: 8, long_click: "*"}
      #- {click: 9, long_click: "("}
      #- {click: 0, long_click: ")"}
      # 第二行
      - {click: q, long_click: "`"}
      - {click: w, long_click: "!"}
```
