### ISSUE TITLE
CI: use Actions secrets store keystore

### ISSUE THREAD

**Issue by wxyzh** [osfans/trime#974]
需要在 Repository secrets中添加以下变量```KEYSTORE```,```SIGNING_KEY_ALIAS```,```SIGNING_KEY_PASSWORD```,```SIGNING_STORE_PASSWORD```
其中 ```KEYSTORE``` 为 base64编码

我直接使用使用base64-to-file 去转存keystore，而且直接用了绝对路径
CI片段如下：
```
      - name: Decode keystore 
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'keystore/test.jks'
          fileDir: '/home/runner/work/_temp/'
          encodedString: ${{ secrets.KEYSTORE }}
          
      - name: create keystore and properties file for signing the app   
        run: |
          echo "storeFile=/home/runner/work/_temp/keystore/test.jks" >> /home/runner/work/trime/trime/keystore.properties
          echo "keyAlias=$SIGNING_KEY_ALIAS" >> /home/runner/work/trime/trime/keystore.properties
          echo "storePassword=$SIGNING_STORE_PASSWORD" >> /home/runner/work/trime/trime/keystore.properties
          echo "keyPassword=$SIGNING_KEY_PASSWORD" >> /home/runner/work/trime/trime/keystore.properties
          #ls /home/runner/work/trime/trime/app
          #cat /home/runner/work/trime/trime/app/keystore.properties
          
        env: 
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
```

为了获得更好的性能建议将jni编译为非debug #926
